### PR TITLE
Feature review top n genes

### PR DESCRIPTION
**Pull request by adityaekawade**

### CODE REVIEW

**Comment by adityaekawade** [comment]
This PR is to add a new feature, allowing to review genes from the "phenotype step" and pass the selected top N genes to "review variants" step. Issue #252 . 

To test: 
Use the branch `review-n-genes` (https://github.com/iobio/gene.iobio.vue/tree/review-n-genes) from gene.iobio repo. 
Do `npm install` as the `iobio-phenotype-extractor-vue` package has been updated. 
Run demo data > Go to `select phenotypes`. 
Add genes `RAI1, PDHA1`, select them by checking the add checkbox on their respective rows. Or use the demo note to generate the genelist, and to test select the top 10 genes to select genes for first time. 
Click the add button!
Screen Shot 2020-09-17 at 1 46 40 PM
Go to the "review variants" step. There should be alertify warning to either update the list or cancel. Select OK. 
The number of genes should be updated and if variants are found, the variant count should also be updated.

**Comment by WilliamRichards2017** [comment]
Looks good and appears to work as expected.  One thing I noticed is that I only added the top 10 genes, but the alertify warning said that 17 genes would be added, which was confusing. I might also add the ability to toggle the add N genes button to add/remove the genes, so its a little bit more clear what happens when you press that button.  I was a bit unsure on the first test if pressing the button added the genes, although the icon change was clear to me the second time testing.  These are minor issues, and I'm happy to approve if you wanna address these small things separately.   Overall looks very good, and the functionality is there.

**Comment by adityaekawade** [comment]
I added a toggle switch to select genes as you had mentioned, I think this will avoid the confusion. So when the toggle switch is enabled the selected genes will be passed to the review variant step. 

Regarding the confusion of the alertify message of 17 genes: 
When you selected the top 10 genes from the gene list, those 10 genes were passed to the review variants step. But there were already 8 more genes added as gene set. And there must have been 1 overlapping gene.. so it showed 17 genes. I have added a tooltip on the toggle switch, so the user is notified that he will be selecting top N genes from the generated gene list using the phenotypes. 

You can test it on: http://dev.clin.iobio.io/

**Review by WilliamRichards2017 — APPROVED** [review]
This looks good to me! I think the toggle is a little clearer for first-time users

**Pull request merged**
