### PR TITLE
Make deleting a gene more obvious

### PR DESCRIPTION
**Pull request by adityaekawade**

### CODE REVIEW

**Comment by tonydisera** [comment]
@adityaekawade , I will merge this pull request.  Just a minor point, but I think we should switch around the buttons.  Yes, then Cancel.
Screen Shot 2020-03-30 at 7 34 33 PM

**Comment by tonydisera** [comment]
Also, I'm wondering based on @AlistairNWard's comment, if he wanted to have a 'delete' link.  I will  go ahead a merge this pull request so we don't hold up progress.

**Comment by adityaekawade** [comment]
Hi @tonydisera  it should be showing Yes and No instead of cancel. Also I will switch around the buttons and push to dev. 
Screen Shot 2020-03-30 at 6 50 23 PM

**Comment by tonydisera** [comment]
I will try to pull this down again to verify that I grabbed the correct pull request.

**Comment by tonydisera** [comment]
Please change the order.  Yes and then No.

**Comment by tonydisera** [comment]
Strange @adityaekawade , since I merged the pull request, I cannot verify that the pull request reflected the most up-to-date code.  It could have been a mistake on my end.  But if it looks okay on stage.clin.iobio.io now.  My main point was that I find it confusing when the order of the buttons are switched around.  In most of our apps we put the affirmative (Yes, Okay, Apply) first, then the negative (Cancel, Close) to the right.

**Pull request merged**
