### PR TITLE
Phenotypist updates

### PR DESCRIPTION
**Pull request by adityaekawade**

### CODE REVIEW

**Comment by anderspitman** [comment]
So it looks like most of them are internal updates, ie dependencies of dependencies. The majority seem to be patch version changes, which are the least concerning. But I'm curious why they're all showing up now. Didn't you already update most of the packages in another merge recently @adityaekawade?

**Comment by adityaekawade** [comment]
There is actually only one dependency update of `iobio-phenotype-extractor-vue`. 
 I had deleted the package-lock.json and did an npm install after Will's code was merged into clin-component. I assume most of the internal dependencies got upgraded during this process and hence we see so many additions and deletions in package-lock.json. This should not have any effect on the app.  I have given it a test, seems to be working as expected. It can be merged. I have also deployed it on dev version so you can also try it on http://dev.clin.iobio.io/

**Comment by anderspitman** [comment]
I agree it probably won't break the app, but we've had problems in the past with dependencies of dependencies breaking things. It broke the entire Mosaic build at one point. Is there no way to recover the old package-lock.json?

**Comment by anderspitman** [comment]
If not it's probably ok. I'd put the risk at low, but should still do a little extra testing to be sure.

**Comment by adityaekawade** [comment]
I can copy the package-lock.json from `clin-components` which is the older version, and then update my component from npm. I guess it will still change the package-lock.json, but there won't be so many additions/ deletions.

**Comment by adityaekawade** [comment]
I have pushed a new commit to this PR. It uses the new backend for phenotype-extractor service (phenotypist). Thanks @anderspitman  for your help!

**Pull request merged**
